apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-demo
  namespace: test-pipelines
spec:
  pipelineRef:
    name: test-pipeline

  params:

    - name: github_url
      value: "https://github.com/xavierpravin/terraform-sample.git"
    - name: tf_action
      value: plan
    - name: SUBSCRIPTION_ID
      type: string
    
  workspaces:
    - name: pipeline-ws
      emptyDir: {}
    
