apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
  namespace: test-pipelines
spec:
  workspaces:
    - name: pipeline-ws
    - name: sonar-settings
  params:
    - name: github_url
      type: string
    - name: tf_action
      type: string
    - name: SUBSCRIPTION_ID
      type: string  
    - name: subdirectory
      type: string  
    - name: azure_spn_name
      type: string  
      
  tasks:
  - name: terraform-primary
    taskRef:
      name: ingressterraform-primary
    params:
      - name: github_url
        value: $(params.github_url)
      - name: tf_action
        value: $(params.tf_action)
      - name: SUBSCRIPTION_ID
        value: $(params.SUBSCRIPTION_ID)
      - name: subdirectory
        value: $(params.subdirectory)
      - name: azure_spn_name
        value: $(params.azure_spn_name)
    workspaces:
      - name: task-ws
        workspace: pipeline-ws
      
